<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="OpenStudio" Version="3.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SAM.Analytical.OpenStudio.Benchmark\SAM.Analytical.OpenStudio.Benchmark.csproj" />
    <ProjectReference Include="..\..\SAM_OpenStudio\SAM.Core.OpenStudio\SAM.Core.OpenStudio.csproj" />
    <ProjectReference Include="..\..\SAM_OpenStudio\SAM.Geometry.OpenStudio\SAM.Geometry.OpenStudio.csproj" />
    <ProjectReference Include="..\..\SAM_OpenStudio\SAM.Analytical.OpenStudio\SAM.Analytical.OpenStudio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SAM.Analytical.Benchmark">
      <HintPath>..\..\..\SAM_Validation\build\SAM.Analytical.Benchmark.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Core">
      <HintPath>..\..\..\SAM\build\SAM.Core.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Geometry">
      <HintPath>..\..\..\SAM\build\SAM.Geometry.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Analytical">
      <HintPath>..\..\..\SAM\build\SAM.Analytical.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Architectural">
      <HintPath>..\..\..\SAM\build\SAM.Architectural.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Weather">
      <HintPath>..\..\..\SAM\build\SAM.Weather.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
